//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Consumablesstock')
export class ConsumablesstockEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  consumableName: string;

  @Column('integer', { nullable: true })
  quantity: number;

  @Column('date', { nullable: true })
  restockDate: Date;

  @Column('text', { nullable: true })
  vendor: string;

  @Column('real', { nullable: true })
  rate: number;
}
