//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Customers')
export class CustomersEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  name: string;

  @Column('text', { nullable: true })
  phoneWhatsappNumber: string;

  @Column('text', { nullable: true })
  addressLine1: string;

  @Column('text', { nullable: true })
  addressLine2: string;

  @Column('text', { nullable: true })
  city: string;

  @Column('text', { nullable: true })
  comments: string;
}
