//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Returnedorders')
export class ReturnedordersEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  order: number;

  @Column('integer', { nullable: true })
  product: number;

  @Column('text', { nullable: true })
  reasonForReturn: string;

  @Column('date', { nullable: true })
  date: Date;

  @Column('text', { nullable: true })
  status: string;

  @Column('bool', { nullable: true })
  recoverable: boolean;

  @Column('bool', { nullable: true })
  totalLoss: boolean;

  @Column('real', { nullable: true })
  recoveryCost: number;
}
