//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Shippingexpenses')
export class ShippingexpensesEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  order: number;

  @Column('text', { nullable: true })
  customerTown: string;

  @Column('text', { nullable: true })
  shippingProvider: string;

  @Column('real', { nullable: true })
  cost: number;

  @Column('date', { nullable: true })
  date: Date;
}
