//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Whatsappchat')
export class WhatsappchatEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  customer: number;

  @Column('text', { nullable: true })
  message: string;

  @Column('date', { nullable: true })
  dateTime: Date;

  @Column('text', { nullable: true })
  status: string;
}
