//Source code generated by AppGPT (www.appgpt.tech)

//Class to create tables and seed new database
import { DataSource } from 'typeorm';
import { DBConfiguration } from './Configuration';
import { SettingsEntity } from './db/Settings.entity';
//autogenerate imports based on resources
import { ProductsEntity } from './db/Products.entity';
import { ProductcategoriesEntity } from './db/Productcategories.entity';
import { CustomersEntity } from './db/Customers.entity';
import { ProductstockEntity } from './db/Productstock.entity';
import { ConsumablesstockEntity } from './db/Consumablesstock.entity';
import { ReviewsEntity } from './db/Reviews.entity';
import { VendorsEntity } from './db/Vendors.entity';
import { DiscountsEntity } from './db/Discounts.entity';
import { OverheadsEntity } from './db/Overheads.entity';
import { ShippingexpensesEntity } from './db/Shippingexpenses.entity';
import { ReturnedordersEntity } from './db/Returnedorders.entity';
import { WhatsappchatEntity } from './db/Whatsappchat.entity';

export class Database {
  static dbConfiguration: DBConfiguration;
  public static ds: DataSource;

  static async Initialize(dbConfiguration: DBConfiguration) {
    Database.dbConfiguration = dbConfiguration;
    let dbConfig: any = dbConfiguration as any;
    //Autogenerate entities array from resource names

    dbConfig.entities = [
      SettingsEntity,
      ProductsEntity,
      ProductcategoriesEntity,
      CustomersEntity,
      ProductstockEntity,
      ConsumablesstockEntity,
      ReviewsEntity,
      VendorsEntity,
      DiscountsEntity,
      OverheadsEntity,
      ShippingexpensesEntity,
      ReturnedordersEntity,
      WhatsappchatEntity,
    ];
    Database.ds = new DataSource(dbConfig);
    await Database.ds.initialize();

    //TODO: Drop all tables

    await Database.Seed();
  }
  static async Seed() {
    let data: any = {
      Products: [
        {
          perfumeName: 'Amber Oud Essence',
          placeholderPicture: 'https://images.unsplash.com/photo-amber-oud.jpg',
          price: 4500,
          description:
            'A luxurious blend of amber and oud, offering a warm, woody aroma perfect for evening wear.',
        },
        {
          perfumeName: 'Citrus Blossom Mist',
          placeholderPicture:
            'https://images.unsplash.com/photo-citrus-blossom.jpg',
          price: 3200.5,
          description:
            'A refreshing fragrance with notes of lemon, orange blossom, and a hint of musk for a lively daytime scent.',
        },
        {
          perfumeName: 'Velvet Rose Petals',
          placeholderPicture:
            'https://images.unsplash.com/photo-velvet-rose.jpg',
          price: 3999.99,
          description:
            'Soft and romantic, this perfume combines rose petals with subtle vanilla for a timeless floral bouquet.',
        },
        {
          perfumeName: 'Oceanic Breeze',
          placeholderPicture:
            'https://images.unsplash.com/photo-oceanic-breeze.jpg',
          price: 2800,
          description:
            'A crisp, aquatic scent reminiscent of sea air, with hints of jasmine and sandalwood for a clean finish.',
        },
        {
          perfumeName: 'Mystic Spice Elixir',
          placeholderPicture:
            'https://images.unsplash.com/photo-mystic-spice.jpg',
          price: 5200.75,
          description:
            'An exotic fusion of spices, incense, and patchouli, creating a mysterious and captivating fragrance.',
        },
      ],
      Productcategories: [
        {
          categoryName: 'Perfumes',
          description:
            'A curated selection of fragrances for men, women, and children, featuring both classic and contemporary scents.',
        },
        {
          categoryName: 'Candles and Incense',
          description:
            'Scented candles and incense sticks to create a calming and aromatic atmosphere in any space.',
        },
        {
          categoryName: 'Organic Oils',
          description:
            'Pure essential oils and oil blends for aromatherapy, personal care, and wellness.',
        },
        {
          categoryName: 'Oil Cocktails',
          description:
            'Specially formulated oil blends designed for hair growth, scalp nourishment, and overall hair health.',
        },
        {
          categoryName: 'Gift Sets',
          description:
            'Beautifully packaged sets combining perfumes, candles, and oils, perfect for gifting on any occasion.',
        },
      ],
      Customers: [
        {
          name: 'Ayesha Khan',
          phoneWhatsappNumber: '+92 300 1234567',
          addressLine1: 'House 12, Street 5',
          addressLine2: 'Sector F-8',
          city: 'Islamabad',
          comments: 'Heavy shopper, prefers floral scents.',
        },
        {
          name: 'Bilal Ahmed',
          phoneWhatsappNumber: '+92 321 9876543',
          addressLine1: 'Flat 3B, Gulshan Apartments',
          addressLine2: 'Block 7',
          city: 'Karachi',
          comments: 'First order, requested gift wrap.',
        },
        {
          name: 'Sadia Malik',
          phoneWhatsappNumber: '+92 333 4567890',
          addressLine1: '123 Model Town',
          addressLine2: 'Near Main Market',
          city: 'Lahore',
          comments: 'Complainant, delayed delivery last time.',
        },
        {
          name: 'Usman Tariq',
          phoneWhatsappNumber: '+92 345 1122334',
          addressLine1: 'House 45, Street 10',
          addressLine2: 'Satellite Town',
          city: 'Rawalpindi',
          comments: 'Avoid this one, multiple returns.',
        },
        {
          name: 'Fatima Noor',
          phoneWhatsappNumber: '+92 312 9988776',
          addressLine1: 'Plot 22, Phase 4',
          addressLine2: 'DHA',
          city: 'Multan',
          comments: 'Regular customer, positive feedback.',
        },
      ],
      Productstock: [
        { product: 1, quantity: 25, restockDate: '2024-06-10T09:00:00Z' },
        { product: 2, quantity: 8, restockDate: '2024-06-15T14:30:00Z' },
        { product: 3, quantity: 50, restockDate: '2024-06-08T11:45:00Z' },
        { product: 4, quantity: 0, restockDate: '2024-06-20T16:00:00Z' },
        { product: 5, quantity: 12, restockDate: '2024-06-12T10:15:00Z' },
      ],
      Consumablesstock: [
        {
          consumableName: 'Amber Glass Bottles 50ml',
          quantity: 120,
          restockDate: '2024-06-10T00:00:00Z',
          vendor: 'Karachi Packaging Supplies',
          rate: 45.5,
        },
        {
          consumableName: 'Cotton Wicks',
          quantity: 500,
          restockDate: '2024-06-05T00:00:00Z',
          vendor: 'Lahore Candle Makers',
          rate: 1.25,
        },
        {
          consumableName: 'Essential Oil Droppers',
          quantity: 200,
          restockDate: '2024-06-12T00:00:00Z',
          vendor: 'Islamabad Essentials',
          rate: 12,
        },
        {
          consumableName: 'Perfume Spray Pumps',
          quantity: 350,
          restockDate: '2024-06-08T00:00:00Z',
          vendor: 'Vendor Solutions PK',
          rate: 8.75,
        },
        {
          consumableName: 'Gift Packaging Boxes',
          quantity: 75,
          restockDate: '2024-06-03T00:00:00Z',
          vendor: 'Elegant Wraps',
          rate: 60,
        },
      ],
      Reviews: [
        {
          product: 1,
          customer: 3,
          rating: 5,
          reviewText:
            'Absolutely love this perfume! The scent lasts all day and I get so many compliments.',
          date: '2024-06-12T14:23:00Z',
        },
        {
          product: 2,
          customer: 1,
          rating: 4,
          reviewText:
            'The candle smells amazing and fills the whole room. Will definitely buy again.',
          date: '2024-06-10T09:15:00Z',
        },
        {
          product: 3,
          customer: 4,
          rating: 3,
          reviewText:
            'The oil is nice but the bottle was smaller than expected.',
          date: '2024-06-08T17:45:00Z',
        },
        {
          product: 4,
          customer: 2,
          rating: 5,
          reviewText: 'My kids love the fragrance! Safe and gentle for them.',
          date: '2024-06-11T11:05:00Z',
        },
        {
          product: 5,
          customer: 5,
          rating: 2,
          reviewText:
            'Incense sticks burn too quickly and the scent is too mild for my taste.',
          date: '2024-06-09T19:30:00Z',
        },
      ],
      Vendors: [
        {
          whatsappnumber: '+923001234567',
          vendorrating: 'Reliable supplier, always delivers on time.',
        },
        {
          whatsappnumber: '+923112223334',
          vendorrating: 'Excellent quality, responsive on WhatsApp.',
        },
        {
          whatsappnumber: '+923214445556',
          vendorrating: 'Occasional delays, but good communication.',
        },
        {
          whatsappnumber: '+923335556667',
          vendorrating: 'Top-rated vendor for essential oils and candles.',
        },
        {
          whatsappnumber: '+923456667788',
          vendorrating: 'Flexible with bulk orders, highly recommended.',
        },
      ],
      Discounts: [
        {
          product: '1',
          discountType: 'Seasonal',
          description: 'Summer Splash Sale on all perfumes for men.',
          discountAmount: 500,
          discountPercent: 10,
          startDate: '2024-06-01T00:00:00Z',
          endDate: '2024-06-15T23:59:59Z',
        },
        {
          product: '2',
          discountType: 'Clearance',
          description: "Clearance discount on last season's scented candles.",
          discountAmount: 200,
          discountPercent: 15,
          startDate: '2024-06-10T00:00:00Z',
          endDate: '2024-06-20T23:59:59Z',
        },
        {
          product: '3',
          discountType: 'Introductory',
          description:
            'Introductory offer on new organic oil cocktail for hair growth.',
          discountAmount: 150,
          discountPercent: 5,
          startDate: '2024-06-05T00:00:00Z',
          endDate: '2024-06-30T23:59:59Z',
        },
        {
          product: '4',
          discountType: 'Festival',
          description: 'Eid special discount on incense packs.',
          discountAmount: 100,
          discountPercent: 8,
          startDate: '2024-06-15T00:00:00Z',
          endDate: '2024-06-22T23:59:59Z',
        },
        {
          product: '5',
          discountType: 'Bulk Purchase',
          description:
            'Buy 3 or more essential oils and get a special discount.',
          discountAmount: 300,
          discountPercent: 12,
          startDate: '2024-06-01T00:00:00Z',
          endDate: '2024-06-30T23:59:59Z',
        },
      ],
      Overheads: [
        {
          overheadType: 'Food and entertainment',
          description:
            'Team lunch at Aroma Bistro after monthly review meeting.',
          amount: 4200.5,
          date: '2024-06-10T13:30:00',
        },
        {
          overheadType: 'Transportation',
          description:
            'Courier charges for express delivery to Karachi branch.',
          amount: 1850,
          date: '2024-06-08T09:15:00',
        },
        {
          overheadType: 'Fines and fees',
          description: 'Late payment penalty for utility bill.',
          amount: 350,
          date: '2024-06-05T16:45:00',
        },
        {
          overheadType: 'Other',
          description:
            'Office supplies restocking (stationery and cleaning items).',
          amount: 2750.75,
          date: '2024-06-03T11:00:00',
        },
        {
          overheadType: 'Other',
          description: 'Marketing expense for Eid promotional flyers.',
          amount: 3200,
          date: '2024-06-01T14:20:00',
        },
      ],
      Shippingexpenses: [
        {
          order: 1,
          customerTown: 'Karachi',
          shippingProvider: 'Leopard Courier',
          cost: 350,
          date: '2024-06-13T14:10:00Z',
        },
        {
          order: 2,
          customerTown: 'Lahore',
          shippingProvider: 'TCS',
          cost: 420.5,
          date: '2024-06-12T11:45:00Z',
        },
        {
          order: 3,
          customerTown: 'Islamabad',
          shippingProvider: 'Pakistan Post',
          cost: 280,
          date: '2024-06-10T16:30:00Z',
        },
        {
          order: 4,
          customerTown: 'Multan',
          shippingProvider: 'BlueEx',
          cost: 390.75,
          date: '2024-06-09T09:20:00Z',
        },
        {
          order: 5,
          customerTown: 'Faisalabad',
          shippingProvider: 'M&P',
          cost: 310,
          date: '2024-06-11T13:05:00Z',
        },
      ],
      Returnedorders: [
        {
          order: 1,
          product: 3,
          reasonForReturn:
            'Bottle leaked during shipping, resulting in significant product loss.',
          date: '2024-06-12T10:15:00Z',
          status: 'Processing',
          recoverable: false,
          totalLoss: true,
          recoveryCost: 0,
        },
        {
          order: 2,
          product: 2,
          reasonForReturn: 'Customer received the wrong fragrance variant.',
          date: '2024-06-10T14:30:00Z',
          status: 'Returned',
          recoverable: true,
          totalLoss: false,
          recoveryCost: 150,
        },
        {
          order: 3,
          product: 5,
          reasonForReturn: 'Damaged packaging and broken bottle on arrival.',
          date: '2024-06-08T09:45:00Z',
          status: 'Refunded',
          recoverable: false,
          totalLoss: true,
          recoveryCost: 0,
        },
        {
          order: 4,
          product: 1,
          reasonForReturn:
            'Customer allergic reaction to product, returned unopened.',
          date: '2024-06-11T16:20:00Z',
          status: 'Inspected',
          recoverable: true,
          totalLoss: false,
          recoveryCost: 50,
        },
        {
          order: 5,
          product: 4,
          reasonForReturn: 'Product expired before delivery.',
          date: '2024-06-09T12:00:00Z',
          status: 'Disposed',
          recoverable: false,
          totalLoss: true,
          recoveryCost: 0,
        },
      ],
      Whatsappchat: [
        {
          customer: '1',
          message:
            'Hi, I would like to know if the Rose Oud perfume is available in stock?',
          dateTime: '2024-06-10T09:15:23Z',
          status: 'unread',
        },
        {
          customer: '3',
          message:
            'Thank you for the quick delivery! The candles smell amazing.',
          dateTime: '2024-06-09T18:42:10Z',
          status: 'read',
        },
        {
          customer: '2',
          message:
            'Can I get a discount if I order 3 bottles of the Jasmine Mist oil?',
          dateTime: '2024-06-08T14:27:55Z',
          status: 'unread',
        },
        {
          customer: '5',
          message:
            'I received a damaged bottle. How can I return or exchange it?',
          dateTime: '2024-06-07T11:03:47Z',
          status: 'pending',
        },
        {
          customer: '4',
          message:
            "Is there a way to track my order? I haven't received any updates.",
          dateTime: '2024-06-06T16:30:12Z',
          status: 'read',
        },
      ],
    };
    //Autogenerate multiple such calls ie for each resource and its data object
    let isSeeded = await this.IsSeeded();
    //if (!isSeeded) {
    //forcing app recreation
    if (true) {
      console.log('   Seeding database...');
      await this.SeedResource('ProductsEntity', data.Products);
      await this.SeedResource(
        'ProductcategoriesEntity',
        data.Productcategories,
      );
      await this.SeedResource('CustomersEntity', data.Customers);
      await this.SeedResource('ProductstockEntity', data.Productstock);
      await this.SeedResource('ConsumablesstockEntity', data.Consumablesstock);
      await this.SeedResource('ReviewsEntity', data.Reviews);
      await this.SeedResource('VendorsEntity', data.Vendors);
      await this.SeedResource('DiscountsEntity', data.Discounts);
      await this.SeedResource('OverheadsEntity', data.Overheads);
      await this.SeedResource('ShippingexpensesEntity', data.Shippingexpenses);
      await this.SeedResource('ReturnedordersEntity', data.Returnedorders);
      await this.SeedResource('WhatsappchatEntity', data.Whatsappchat);
      await this.SeedResource('SettingsEntity', {
        settingname: 'isSeeded',
        settingvalue: 'true',
      });
    } else {
      console.log('   Database seeded already!');
    }
  }
  static async IsSeeded() {
    const repo = Database.ds.getRepository('SettingsEntity');
    let rec: any = await repo.findOne({
      select: {
        settingname: true,
        settingvalue: true,
      },
      where: {
        settingname: 'isSeeded',
      },
    });
    if (rec && rec.settingvalue) return true;
    return false;
  }
  static async SeedResource(resourceName: any, resourceData: any) {
    const repo = Database.ds.getRepository(resourceName);
    //await repo.clear();
    console.log('   Seeding table ' + resourceName);
    await repo.upsert(resourceData, ['id']);
  }
}
