//Source code generated by AppGPT (www.appgpt.tech)
import { Admin, Resource, CustomRoutes } from 'react-admin';
import { customDataProvider } from './dataProvider';
import fakeDataProvider from 'ra-data-fakerest';
import { Dashboard } from './dashboard';
import { authProvider, apInitialize } from './authProvider';
import { i18nProvider } from './i18nProvider';
import LoginPage, { Login } from './Login';
import data from './data';
import {
  ProductsList,
  ProductsCreate,
  ProductsEdit,
} from './resources/Products';
import {
  ProductcategoriesList,
  ProductcategoriesCreate,
  ProductcategoriesEdit,
} from './resources/Productcategories';
import {
  CustomersList,
  CustomersCreate,
  CustomersEdit,
} from './resources/Customers';
import {
  ProductstockList,
  ProductstockCreate,
  ProductstockEdit,
} from './resources/Productstock';
import {
  ConsumablesstockList,
  ConsumablesstockCreate,
  ConsumablesstockEdit,
} from './resources/Consumablesstock';
import { ReviewsList, ReviewsCreate, ReviewsEdit } from './resources/Reviews';
import { VendorsList, VendorsCreate, VendorsEdit } from './resources/Vendors';
import {
  DiscountsList,
  DiscountsCreate,
  DiscountsEdit,
} from './resources/Discounts';
import {
  OverheadsList,
  OverheadsCreate,
  OverheadsEdit,
} from './resources/Overheads';
import {
  ShippingexpensesList,
  ShippingexpensesCreate,
  ShippingexpensesEdit,
} from './resources/Shippingexpenses';
import {
  ReturnedordersList,
  ReturnedordersCreate,
  ReturnedordersEdit,
} from './resources/Returnedorders';
import {
  WhatsappchatList,
  WhatsappchatCreate,
  WhatsappchatEdit,
} from './resources/Whatsappchat';
import ProductsIcon from '@mui/icons-material/LocalMall';
import ProductcategoriesIcon from '@mui/icons-material/Category';
import CustomersIcon from '@mui/icons-material/Person';
import ProductstockIcon from '@mui/icons-material/Inventory';
import ConsumablesstockIcon from '@mui/icons-material/Inventory2';
import ReviewsIcon from '@mui/icons-material/RateReview';
import VendorsIcon from '@mui/icons-material/Storefront';
import DiscountsIcon from '@mui/icons-material/Percent';
import OverheadsIcon from '@mui/icons-material/ReceiptLong';
import ShippingexpensesIcon from '@mui/icons-material/LocalShipping';
import ReturnedordersIcon from '@mui/icons-material/AssignmentReturn';
import WhatsappchatIcon from '@mui/icons-material/WhatsApp';
// SUPERTOKENS
import React from 'react';
import SuperTokens, {
  SuperTokensWrapper,
  getSuperTokensRoutesForReactRouterDom,
} from 'supertokens-auth-react';
import ThirdPartyPasswordless from 'supertokens-auth-react/recipe/thirdpartypasswordless';
import Session from 'supertokens-auth-react/recipe/session';
import { BrowserRouter, Routes, Route, Link } from 'react-router-dom';
import * as reactRouterDom from 'react-router-dom';
let sessionFn = Session.init();
SuperTokens.init({
  appInfo: {
    appName: import.meta.env.VITE_SUPERTOKENS_APPNAME,
    apiDomain: import.meta.env.VITE_BACKEND_DOMAIN,
    websiteDomain: import.meta.env.VITE_SUPERTOKENS_WEBSITEDOMAIN,
    apiBasePath: import.meta.env.VITE_BACKEND_APIPATH + '/auth',
    websiteBasePath: import.meta.env.VITE_SUPERTOKENS_WEBSITEBASEPATH,
  },
  recipeList: [
    ThirdPartyPasswordless.init({
      contactMethod: 'EMAIL',
      signInUpFeature: {
        providers: [
          ThirdPartyPasswordless.Github.init(),
          //ThirdPartyPasswordless.Google.init(),
          //ThirdPartyPasswordless.Facebook.init(),
          //ThirdPartyPasswordless.Apple.init(),
        ],
      },
    }),
    sessionFn,
  ],
});
apInitialize(Session);
// END SUPERTOKENS
let dataProvider: any;
if (import.meta.env.VITE_USE_BACKEND_DATA === 'true') {
  dataProvider = customDataProvider(
    import.meta.env.VITE_BACKEND_DOMAIN +
      import.meta.env.VITE_BACKEND_APIPATH +
      '/proxy',
  );
} else {
  dataProvider = fakeDataProvider(data.defaultData);
}

const App = () => (
  <SuperTokensWrapper>
    <BrowserRouter basename="/a82d94c47">
      <Admin
        authProvider={
          import.meta.env.VITE_ENVIRONMENT != 'DEV' ? authProvider : undefined
        }
        requireAuth
        loginPage={LoginPage}
        dataProvider={dataProvider}
        i18nProvider={i18nProvider}
        dashboard={Dashboard}
      >
        <Resource
          name="Products"
          options={{ label: 'Products' }}
          list={ProductsList}
          create={ProductsCreate}
          edit={ProductsEdit}
          recordRepresentation="id"
          icon={ProductsIcon}
        />
        <Resource
          name="Productcategories"
          options={{ label: 'Product Categories' }}
          list={ProductcategoriesList}
          create={ProductcategoriesCreate}
          edit={ProductcategoriesEdit}
          recordRepresentation="id"
          icon={ProductcategoriesIcon}
        />
        <Resource
          name="Customers"
          options={{ label: 'Customers' }}
          list={CustomersList}
          create={CustomersCreate}
          edit={CustomersEdit}
          recordRepresentation="name"
          icon={CustomersIcon}
        />
        <Resource
          name="Productstock"
          options={{ label: 'Product Stock' }}
          list={ProductstockList}
          create={ProductstockCreate}
          edit={ProductstockEdit}
          recordRepresentation="id"
          icon={ProductstockIcon}
        />
        <Resource
          name="Consumablesstock"
          options={{ label: 'Consumables Stock' }}
          list={ConsumablesstockList}
          create={ConsumablesstockCreate}
          edit={ConsumablesstockEdit}
          recordRepresentation="id"
          icon={ConsumablesstockIcon}
        />
        <Resource
          name="Reviews"
          options={{ label: 'Reviews' }}
          list={ReviewsList}
          create={ReviewsCreate}
          edit={ReviewsEdit}
          recordRepresentation="id"
          icon={ReviewsIcon}
        />
        <Resource
          name="Vendors"
          options={{ label: 'Vendors' }}
          list={VendorsList}
          create={VendorsCreate}
          edit={VendorsEdit}
          recordRepresentation="id"
          icon={VendorsIcon}
        />
        <Resource
          name="Discounts"
          options={{ label: 'Discounts' }}
          list={DiscountsList}
          create={DiscountsCreate}
          edit={DiscountsEdit}
          recordRepresentation="id"
          icon={DiscountsIcon}
        />
        <Resource
          name="Overheads"
          options={{ label: 'Overheads' }}
          list={OverheadsList}
          create={OverheadsCreate}
          edit={OverheadsEdit}
          recordRepresentation="id"
          icon={OverheadsIcon}
        />
        <Resource
          name="Shippingexpenses"
          options={{ label: 'Shipping Expenses' }}
          list={ShippingexpensesList}
          create={ShippingexpensesCreate}
          edit={ShippingexpensesEdit}
          recordRepresentation="shippingProvider"
          icon={ShippingexpensesIcon}
        />
        <Resource
          name="Returnedorders"
          options={{ label: 'Returned Orders' }}
          list={ReturnedordersList}
          create={ReturnedordersCreate}
          edit={ReturnedordersEdit}
          recordRepresentation="id"
          icon={ReturnedordersIcon}
        />
        <Resource
          name="Whatsappchat"
          options={{ label: 'Whatsapp Chat' }}
          list={WhatsappchatList}
          create={WhatsappchatCreate}
          edit={WhatsappchatEdit}
          recordRepresentation="id"
          icon={WhatsappchatIcon}
        />
        <CustomRoutes noLayout>
          {/*This renders the login UI on the /auth route*/}
          {getSuperTokensRoutesForReactRouterDom(reactRouterDom)}
          {/*Your app routes*/}
        </CustomRoutes>
      </Admin>
    </BrowserRouter>
  </SuperTokensWrapper>
);

export default App;
