//Source code generated by AppGPT (www.appgpt.tech)
import { Card, CardContent, CardHeader } from '@mui/material';
export const Dashboard = () => (
  <Card>
    <CardHeader title="ScentStudio" />
    <CardContent>
      ScentStudio is an ecommerce platform selling perfumes for men, women, and
      children, as well as essential oils, scented candles, incense, and oil
      cocktails for hair growth and other uses.
      <p>
        Built with{' '}
        <a
          href="https://www.appgpt.tech"
          target="_blank"
          rel="noopener noreferrer"
        >
          AppGPT
        </a>
      </p>
    </CardContent>
  </Card>
);
