//Source code generated by AppGPT (www.appgpt.tech)
import { GetListParams } from 'ra-core';
import postgrestRestProvider from '@promitheus/ra-data-postgrest';
import qs from 'qs';

const fieldConfig = {
  Products: [
    {
      field: 'perfumeName',
      datatype: 'String',
    },
    {
      field: 'placeholderPicture',
      datatype: 'String',
    },
    {
      field: 'price',
      datatype: 'Real',
    },
    {
      field: 'description',
      datatype: 'String',
    },
    {
      field: 'id',
      datatype: 'Integer',
    },
  ],
  Productcategories: [
    {
      field: 'categoryName',
      datatype: 'String',
    },
    {
      field: 'description',
      datatype: 'String',
    },
    {
      field: 'id',
      datatype: 'Integer',
    },
  ],
  Customers: [
    {
      field: 'name',
      datatype: 'String',
    },
    {
      field: 'phoneWhatsappNumber',
      datatype: 'String',
    },
    {
      field: 'addressLine1',
      datatype: 'String',
    },
    {
      field: 'addressLine2',
      datatype: 'String',
    },
    {
      field: 'city',
      datatype: 'String',
    },
    {
      field: 'comments',
      datatype: 'String',
    },
    {
      field: 'id',
      datatype: 'Integer',
    },
  ],
  Productstock: [
    {
      field: 'product',
      datatype: 'Integer',
    },
    {
      field: 'quantity',
      datatype: 'Integer',
    },
    {
      field: 'restockDate',
      datatype: 'DateTime',
    },
    {
      field: 'id',
      datatype: 'Integer',
    },
  ],
  Consumablesstock: [
    {
      field: 'consumableName',
      datatype: 'String',
    },
    {
      field: 'quantity',
      datatype: 'Integer',
    },
    {
      field: 'restockDate',
      datatype: 'DateTime',
    },
    {
      field: 'vendor',
      datatype: 'String',
    },
    {
      field: 'rate',
      datatype: 'Real',
    },
    {
      field: 'id',
      datatype: 'Integer',
    },
  ],
  Reviews: [
    {
      field: 'product',
      datatype: 'Integer',
    },
    {
      field: 'customer',
      datatype: 'Integer',
    },
    {
      field: 'rating',
      datatype: 'Integer',
    },
    {
      field: 'reviewText',
      datatype: 'String',
    },
    {
      field: 'date',
      datatype: 'DateTime',
    },
    {
      field: 'id',
      datatype: 'Integer',
    },
  ],
  Vendors: [
    {
      field: 'whatsappnumber',
      datatype: 'String',
    },
    {
      field: 'vendorrating',
      datatype: 'String',
    },
    {
      field: 'id',
      datatype: 'Integer',
    },
  ],
  Discounts: [
    {
      field: 'product',
      datatype: 'Integer',
    },
    {
      field: 'discountType',
      datatype: 'String',
    },
    {
      field: 'description',
      datatype: 'String',
    },
    {
      field: 'discountAmount',
      datatype: 'Real',
    },
    {
      field: 'discountPercent',
      datatype: 'Real',
    },
    {
      field: 'startDate',
      datatype: 'DateTime',
    },
    {
      field: 'endDate',
      datatype: 'DateTime',
    },
    {
      field: 'id',
      datatype: 'Integer',
    },
  ],
  Overheads: [
    {
      field: 'overheadType',
      datatype: 'String',
    },
    {
      field: 'description',
      datatype: 'String',
    },
    {
      field: 'amount',
      datatype: 'Real',
    },
    {
      field: 'date',
      datatype: 'DateTime',
    },
    {
      field: 'id',
      datatype: 'Integer',
    },
  ],
  Shippingexpenses: [
    {
      field: 'order',
      datatype: 'Integer',
    },
    {
      field: 'customerTown',
      datatype: 'String',
    },
    {
      field: 'shippingProvider',
      datatype: 'String',
    },
    {
      field: 'cost',
      datatype: 'Real',
    },
    {
      field: 'date',
      datatype: 'DateTime',
    },
    {
      field: 'id',
      datatype: 'Integer',
    },
  ],
  Returnedorders: [
    {
      field: 'order',
      datatype: 'Integer',
    },
    {
      field: 'product',
      datatype: 'Integer',
    },
    {
      field: 'reasonForReturn',
      datatype: 'String',
    },
    {
      field: 'date',
      datatype: 'DateTime',
    },
    {
      field: 'status',
      datatype: 'String',
    },
    {
      field: 'recoverable',
      datatype: 'Boolean',
    },
    {
      field: 'totalLoss',
      datatype: 'Boolean',
    },
    {
      field: 'recoveryCost',
      datatype: 'Real',
    },
    {
      field: 'id',
      datatype: 'Integer',
    },
  ],
  Whatsappchat: [
    {
      field: 'customer',
      datatype: 'Integer',
    },
    {
      field: 'message',
      datatype: 'String',
    },
    {
      field: 'dateTime',
      datatype: 'DateTime',
    },
    {
      field: 'status',
      datatype: 'String',
    },
    {
      field: 'id',
      datatype: 'Integer',
    },
  ],
};

export const customDataProvider = (apiUrl, options = {}) => {
  const baseDataProvider = postgrestRestProvider(apiUrl);
  return {
    ...baseDataProvider,
    getList: async (resource, params) => {
      if (params.filter && params.filter.q) {
        return await GetListQ(resource, params, apiUrl, baseDataProvider);
      } else {
        return baseDataProvider.getList(resource, params);
      }
    },
  };
};

async function GetListQ(
  resource,
  params: Partial<GetListParams> = {},
  apiUrl,
  baseDataProvider,
) {
  const { page, perPage } = params.pagination;
  const { field, order } = params.sort || {};
  const searchText = params.filter.q.toLowerCase();

  let filter = { or: '(id.eq.-1)' }; //return no data if resource has not been configured
  if (fieldConfig[resource]) {
    let searchConditions = fieldConfig[resource].reduce(
      (conditions, { field, datatype }) =>
        conditions +
        (datatype == 'String'
          ? field + '.ilike.%' + searchText + '%,'
          : //Todo: add support for searching other types
            ''),
      '',
    );
    filter = { or: '(' + searchConditions.slice(0, -1) + ')' };
  }
  let query = {
    offset: String((page - 1) * perPage),
    limit: String(perPage),
    // append filters
    ...filter,
  };

  if (field && order) {
    query.order = field + '.' + order.toLowerCase();
  }

  // add header that Content-Range is in returned header
  const options = {
    headers: new Headers({
      Accept: 'application/json',
      Prefer: 'count=exact',
      ...(params.meta?.headers || {}),
      //...useCustomSchema(config.schema, metaSchema, 'GET'),
    }),
  };

  const url = apiUrl + '/' + resource + '?' + qs.stringify(query);
  const response = await fetch(url, options);
  if (!response.ok) {
    const message = 'An error has occured: ' + response.status;
    throw new Error(message);
  }
  if (!response.headers.has('content-range')) {
    throw new Error(
      `The Content-Range header is missing in the HTTP Response. The postgREST data provider expects 
            responses for lists of resources to contain this header with the total number of results to build 
            the pagination. If you are using CORS, did you declare Content-Range in the Access-Control-Expose-Headers header?`,
    );
  }
  const json = await response.json();
  return {
    data: json,
    total: parseInt(response.headers.get('content-range').split('/').pop(), 10),
  };
}
